src/Entity/Staging.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="nnc_staging")
 * @ORM\Entity(repositoryClass="App\Repository\StagingRepository")
 */
class Staging
{

    use IdTrait;

    use DateTrait;

    use NameTrait;

    use UserTrait;

    use DescriptionTrait;

    use ModificationDateTrait;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull(message="NASID nécessaire !")
     * @Assert\Type("string")
     * @Assert\Length(max=255)
     */
    private $nasId;

    /**
     * @ORM\Column( type="boolean" )
     * @Assert\IsTrue(message="License nécessaire !")
     */
    private $license_nasId = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type("string")
     * @Assert\Length(max=255)
     */
    private $contact_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type("string")
     * @Assert\Length(max=20)
     */
    private $contact_phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type("string")
     * @Assert\Length(max=255)
     */
    private $contact_address;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type("string")
     * @Assert\Length(max=20)
     */
    private $contact_zipcode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type("string")
     * @Assert\Length(max=255)
     */
    private $contact_city;

    /**
     * @ORM\Column( type="datetime", nullable=true)
     * @Assert\Date()
     */
    private $delivery_date;

    /**
     * @ORM\Column( type="boolean" )
     */
    private $hoist_standard = true;

    /**
     * @Assert\File(
     *     maxSize = "3k",
     *     mimeTypes = {"application/pdf",
     *          "text/plain",
     *          "application/msword",
     *          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
     *          "application/vnd.openxmlformats-officedocument.presentationml.presentation",
     *          "application/vnd.ms-excel",
     *          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
     *     mimeTypesMessage = "Veuillez déposer un fichier (txt, doc, xls, etc...) valide (3mo maximum)"
     * )
     */
    private $standard_file_upload;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $standard_file_path;

    /**
     * @ORM\Column(type="array")
     * @Assert\NotNull()
     */
    private $staging_type = [];

    /**
     * @ORM\Column( type="boolean", nullable=true )
     */
    private $streamer;

    /**
     * @ORM\Column( type="boolean", nullable=true )
     */
    private $vod;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type("string")
     * @Assert\Length(max=255)
     */
    private $tv_channel_plan;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type("string")
     * @Assert\Length(max=255)
     */
    private $radio_channel_plan;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type("string")
     * @Assert\Length(max=255)
     */
    private $room_list;

    /**
     * @ORM\Column( type="array", nullable=true )
     */
    private $tv_brand = [];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type("string")
     * @Assert\Length(max=255)
     */
    private $gui_type;

    // liste de ssid avec nom / zone
    // la liste doit s'étendre à mesure qu'il ajoute des éléments
    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $ssid_list;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type("string")
     * @Assert\Length(max=255)
     */
    private $head_brand;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $controller_brand;

    /**
     * @ORM\Column(type="boolean")
     */
    private $tv_on_wifi = false;

    // Si Chromcast ET pas de Wifi
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type("string")
     * @Assert\Length(max=255)
     */
    private $ssid_wifi;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type("string")
     * @Assert\Length(max=255)
     */
    private $vlan_wifi;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type("string")
     * @Assert\Length(max=255)
     */
    private $guest_ip;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type("string")
     * @Assert\Length(max=255)
     */
    private $ssid_vlan;

    /**
     * @Assert\File(
     *     maxSize = "3k",
     *     mimeTypes = {"application/pdf",
     *          "text/plain",
     *          "application/msword",
     *          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
     *          "application/vnd.openxmlformats-officedocument.presentationml.presentation",
     *          "application/vnd.ms-excel",
     *          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
     *     mimeTypesMessage = "Veuillez déposer un fichier (txt, doc, xls, etc...) valide (3mo maximum)"
     * )
     */
    private $lan_file_upload;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lan_file_path;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type("string")
     * @Assert\Length(max=255)
     */
    private $lan_file_name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Type("integer")
     */
    private $switch_quantity;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Type("string")
     * @Assert\Length(max=255)
     */
    private $trader;

    /**
     * @return mixed
     */
    public function getNasId()
    {
        return $this->nasId;
    }

    /**
     * @param mixed $nasId
     */
    public function setNasId($nasId): void
    {
        $this->nasId = $nasId;
    }

    /**
     * @return mixed
     */
    public function getContactName()
    {
        return $this->contact_name;
    }

    /**
     * @param mixed $contact_name
     */
    public function setContactName($contact_name): void
    {
        $this->contact_name = $contact_name;
    }

    /**
     * @return mixed
     */
    public function getContactPhone()
    {
        return $this->contact_phone;
    }

    /**
     * @param mixed $contact_phone
     */
    public function setContactPhone($contact_phone): void
    {
        $this->contact_phone = $contact_phone;
    }

    /**
     * @return mixed
     */
    public function getContactAddress()
    {
        return $this->contact_address;
    }

    /**
     * @param mixed $contact_address
     */
    public function setContactAddress($contact_address): void
    {
        $this->contact_address = $contact_address;
    }

    /**
     * @return mixed
     */
    public function getContactZipcode()
    {
        return $this->contact_zipcode;
    }

    /**
     * @param mixed $contact_zipcode
     */
    public function setContactZipcode($contact_zipcode): void
    {
        $this->contact_zipcode = $contact_zipcode;
    }

    /**
     * @return mixed
     */
    public function getContactCity()
    {
        return $this->contact_city;
    }

    /**
     * @param mixed $contact_city
     */
    public function setContactCity($contact_city): void
    {
        $this->contact_city = $contact_city;
    }

    /**
     * @return mixed
     */
    public function getDeliveryDate()
    {
        return $this->delivery_date;
    }

    /**
     * @param mixed $delivery_date
     */
    public function setDeliveryDate($delivery_date): void
    {
        $this->delivery_date = $delivery_date;
    }

    /**
     * @return mixed
     */
    public function getHoistStandard()
    {
        return $this->hoist_standard;
    }

    /**
     * @param mixed $hoist_standard
     */
    public function setHoistStandard($hoist_standard): void
    {
        $this->hoist_standard = $hoist_standard;
    }

    /**
     * @return mixed
     */
    public function getStagingType()
    {
        return $this->staging_type;
    }

    /**
     * @param mixed $staging_type
     */
    public function setStagingType($staging_type): void
    {
        $this->staging_type = $staging_type;
    }

    /**
     * @return mixed
     */
    public function getStreamer()
    {
        return $this->streamer;
    }

    /**
     * @param mixed $streamer
     */
    public function setStreamer($streamer): void
    {
        $this->streamer = $streamer;
    }

    /**
     * @return mixed
     */
    public function getVod()
    {
        return $this->vod;
    }

    /**
     * @param mixed $vod
     */
    public function setVod($vod): void
    {
        $this->vod = $vod;
    }

    /**
     * @return mixed
     */
    public function getTvChannelPlan()
    {
        return $this->tv_channel_plan;
    }

    /**
     * @param mixed $tv_channel_plan
     */
    public function setTvChannelPlan($tv_channel_plan): void
    {
        $this->tv_channel_plan = $tv_channel_plan;
    }

    /**
     * @return mixed
     */
    public function getRadioChannelPlan()
    {

templates/pdf/address.html.twig
{% if datas.client %}
<p>{{ datas.client.name }}</p>
<p>{{ datas.client.description }}<br>
{{ datas.client.street }}<br>
{{ datas.client.city }}<br>
{% endif %}
<br>
le {{ date|date("d/m/Y") }}</p>

templates/pdf/legal.html.twig
<div class="text-center">
    <p>CONCORDELEC</p>
    <p>RCS 444 713 283 00026  APE 725Z TVA Intra-communautaire FR 184 447 132 83</p>
    <p>87 Rue Legendre 75017 PARIS – Tél. : 01 46 27 27 62 – email (commercial) : commercial@concordelec.com</p>
</div>

templates/pdf/template-bill.html.twig
<!DOCTYPE html>
<html xml:lang="fr" lang="fr">
<head>
    <meta charset="utf8mb4"/>

    {#<meta http-equiv="X-UA-Compatible" content="IE=edge">#}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {# Bootstrap v4.0.0 #}
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

    <title>Devis</title>

</head>
<body>

    <div class="container">
        <div>
            <div>
                <img src="{{ nncLogoUrl }}" style="width: 100px">
                <!-- à réactiver quand le partner aura un logo
                    <img src="{{ partnerLogoUrl }}" style="width: 100px">
                -->
            </div>
            <div style="width: 50%; margin-left: 50%;">
                {% include 'pdf/address.html.twig' with {'date': datas.date} %}
            </div>
        </div>
        <div>
            <p>Devis n° {{ datas.number }} - <strong>{{ datas.title }}</strong></p>
            <p style="font-size: 12px; opacity: 0.75; font-style: italic;">(Ce document est édité à titre provisoire et est valable pour une durée de un mois après édition)</p>
        </div>
    </div>

    {% for service in datas.services %}
        <table  class="table table-bordered table-striped">
            <tr>
                <th colspan="4">
                    {{ service.name }}
                </th>
            </tr>
            {% for item in service.datas %}
                <tr>
                    <th>
                        <label>{{ item.name }}</label>
                    </th>
                    <th class="text-center">{{ item.quantity }}</th>
                    <th class="text-center">x {{ item.price }} €</th>
                    <th class="text-center">{{ item.total > 0 ? '= ' ~ item.total ~ ' €' : 'gratuit' }}</th>
                </tr>
            {% endfor %}
        </table>
    {% endfor %}

    {% if datas.description != '' %}
        <p><strong>Commentaire(s)</strong></p>
        <p style="white-space: pre-line">{{ datas.description }}</p>
    {% endif %}

    <table class="table table-bordered table-striped">
        <tr>
            <th class="text-center">
                <label for="bill_total">Total</label>
            </th>
            <th class="text-center">
                {{ datas.price }} € (HT) <br>
                <span style="font-size: 12px; opacity: 0.75; font-style: italic;">(montant hors taxes, la TVA est ajoutée et calculée en fonction de la TVA en rigueur)</span>
            </th>
        </tr>
    </table>

</body>

templates/pdf/template-staging.html.twig
<!DOCTYPE html>
<html xml:lang="fr" lang="fr">
<head>
    <meta charset="utf8mb4"/>

    {#<meta http-equiv="X-UA-Compatible" content="IE=edge">#}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {# Bootstrap v4.0.0 #}
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

    <title>Staging</title>

    <style>
        body { font-size: 12px; font-weight: 400; }
        strong { font-weight: 700; }
        th, p  { margin-bottom: 2px; margin-top: 2px; padding-bottom: 2px; padding-top: 2px; }
    </style>

</head>
<body>

    <table class="table table-bordered table-striped">
        <tr>
            <th colspan="3">
                <span style="font-size: 18px">Fiche de Staging - <strong>{{ staging.name }}</strong></span>
            </th>
            <th>
                <img src="{{ nncLogoUrl }}" style="width: 100px;">
            </th>
        </tr>
        <tr>
            <th>
                <p><strong>NASID</strong></p>
                <p>{{staging.nasId}}</p>
            </th>
            <th>
                <p><strong>Date de livraison</strong></p>
                <p>{{staging.deliveryDate ? staging.deliveryDate|date("d/m/Y") : "non renseigné"}}</p>
            </th>
            <th>
                <p><strong>Type de Staging</strong></p>
                <p>{% for type in staging.stagingType %}
                {{type == 1 ? "TV" : type == 2 ? "Wifi" : type == 3 ? "Chromecast" : type == 4 ? "Lan" : type == 5 ? "Switch" : type == 6 ? "Radio" : ""}}{{loop.last ? "" : ","}}{% endfor %}</p>
            </th>
            <th>
                <p><strong>Standards Hoist</strong></p>
                <p>{{staging.hoistStandard ? "Respectés" : "Non respectés"}}</p>
                {% if not staging.hoistStandard %}
                    <p>(Standard fournis pièce jointe)</p>
                {% endif %}
            </th>
        </tr>
    </table>

    <table class="table table-bordered table-striped">
        <tr>
            <th>Contact</th>
            <th colspan="3">
                <p><strong>Nom</strong> : {{staging.contactName ?? "non renseigné"}} ({{staging.contactPhone ?? "téléphone non renseigné"}})</p>
                <p>{{staging.contactZipcode ?? "(Code Postal non renseigné)"}} - {{staging.contactCity ?? "(Ville non renseigné)"}} : {{staging.contactAddress ?? "(Adresse non renseignée)"}}</p>
            </th>
        </tr>
    </table>

    {# "TV" required #}
    {% if 1 in staging.stagingType %}
        <table class="table table-bordered table-striped">
            <tr>
                <th colspan="4">TV</th>
            </tr>
            <tr>
                <th>
                    <p><strong>Streamer</strong> : {{ staging.streamer ? 'Oui' : 'Non' }}</p>
                </th>
                <th>
                    <p><strong>VOD</strong> : {{ staging.vod ? 'Oui' : 'Non' }}</p>
                </th>
                <th colspan="2">
                    <p><strong>Marque(s) TV</strong> : {% for brand in staging.tvBrand %}{{ brand }}{{loop.last ? "" : ", "}}{% endfor %}</p>
                </th>
            </tr>
            <tr>
                <th colspan="4">
                    <p><strong>Plan chaines TV</strong> : {{ staging.tvChannelPlan }}</p>
                </th>
            </tr>
            <tr>
                <th colspan="4">
                    <p><strong>Liste des chambres</strong> : {{ staging.roomList }}</p>
                </th>
            </tr>
            <tr>
                <th>
                    <p><strong>Type de Gui</strong> : {{ staging.guiType }}</p>
                </th>
            </tr>
        </table>
    {% endif %}

    {# "Wifi" required #}
    {% if 2 in staging.stagingType %}
        <table class="table table-bordered table-striped">
            <tr>
                <th colspan="4">Wifi</th>
            </tr>
            <tr>
                <th>
                    <p><strong>Type de borne</strong> : {{ staging.headBrand }}</p>
                </th>
                <th>
                    <p><strong>Contrôleur de borne</strong> : {{ staging.controllerBrand }}</p>
                </th>
            </tr>
            <tr>
                <th>
                    <p>N'oubliez pas de créer la rate card !</p>
                </th>
                {# "Wifi" and "TV" required #}
                {% if 1 in staging.stagingType %}
                    <th>
                        <p>TV sur le Wifi ? {{ staging.tvOnWifi ? 'Oui' : 'Non' }}</p>
                    </th>
                {% else %}<th></th>{% endif %}
                <th colspan="2"></th>
            </tr>
        </table>
    {% endif %}

    {# "Chromecast" and not "Wifi" required #}
    {% if 3 in staging.stagingType and 2 not in staging.stagingType %}
        <table class="table table-bordered table-striped">
            <tr>
                <th colspan="4">Chromecast</th>
            </tr>
            <tr>
                <th>
                    <p><strong>Vlan Wifi</strong> : {{ staging.vlanWifi }}</p>
                </th>
                <th>
                    <p><strong>Guest IP</strong> : {{ staging.guestIp }}</p>
                </th>
                <th>
                    <p><strong>SSID VLAN</strong> : {{ staging.ssidVlan }}</p>
                </th>
                <th>
                    <p><strong>SSID Wifi</strong> : {{ staging.ssidWifi }}</p>
                </th>
            </tr>
        </table>
    {% endif %}

    {# "Lan" required #}
    {% if 4 in staging.stagingType %}
        <table class="table table-bordered table-striped">
            <tr>
                <th colspan="4">Lan</th>
            </tr>
            <tr>
                <th colspan="4">
                    <p>Informations des services, plan d'adressage, VLAN, DHCP fournis en pièce jointe</p>
                </th>
            </tr>
        </table>
    {% endif %}

    {# "Switch" required #}
    {% if 5 in staging.stagingType %}
        <table class="table table-bordered table-striped">
            <tr>
                <th colspan="4">Switch</th>
            </tr>
            <tr>
                <th>
                    <p><strong>Quantité de switch</strong> : {{ staging.switchQuantity }}</p>
                </th>
                <th>
                    <p><strong>Type de switch</strong> : {{ staging.trader }}</p>
                </th>
                <th colspan="2"></th>
            </tr>
        </table>
    {% endif %}

    {# "Radio" required #}
    {% if 6 in staging.stagingType %}
        <table class="table table-bordered table-striped">
            <tr>
                <th colspan="4">Radio</th>
            </tr>
            <tr>
                <th colspan="4">
                    <p><strong>Plan radios</strong> : {{ staging.radioChannelPlan }}</p>
                </th>
            </tr>
        </table>
    {% endif %}

    {% if staging.description %}
        <table class="table table-bordered table-striped">
            <tr>
                <th colspan="4">Description</th>
            </tr>
            <tr>
                <th colspan="4">
                    <p>{{staging.description}}</p>
                </th>
            </tr>
        </table>
    {% endif %}
</body>

templates/pdf/template.html.twig
<!DOCTYPE html>
<html xml:lang="fr" lang="fr">
<head>
    <meta charset="utf8mb4"/>

    {#<meta http-equiv="X-UA-Compatible" content="IE=edge">#}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {# Bootstrap v4.0.0 #}
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

    {# Pdf Style #}
    <link rel="stylesheet" type="text/css"
          href="{{ asset('css/pdf-style.css') }}">

    <title>Devis</title>

</head>
<body>

    <div class="container">
        <div>
            <div>
                <img src="{{ nncLogoUrl }}" style="width: 100px">
                <!-- à réactiver quand le partner aura un logo
                    <img src="{{ partnerLogoUrl }}" style="width: 100px">
                -->
            </div>
            <div style="width: 50%; margin-left: 50%;">
                {% include 'pdf/address.html.twig' with {'date': datas.date} %}
            </div>
        </div>
        <div>
            <p>Devis n° {{ datas.number }} - <strong>{{ datas.title }}</strong></p>
            <p>(Ce document est édité à titre provisoire)</p>
        </div>
    </div>

    <legend class="mb-4"></legend>

    {% for service in datas.services %}
        <table  class="table table-bordered table-striped">
            <tr>
                <th colspan="4">
                    {{ service.name }}
                </th>
            </tr>
            {% for item in service.datas %}
                <tr>
                    <th>
                        <label>{{ item.name }}</label>
                    </th>
                    <th class="text-center">{{ item.quantity }}</th>
                    <th class="text-center">x {{ item.price }} €</th>
                    <th class="text-center">{{ item.total > 0 ? '= ' ~ item.total ~ ' €' : 'gratuit' }}</th>
                </tr>
            {% endfor %}
        </table>
    {% endfor %}

    {% if datas.description != '' %}
        <p><strong>Commentaire(s)</strong></p>
        <p style="white-space: pre-line">{{ datas.description }}</p>
    {% endif %}

    <table class="table table-bordered table-striped">
        <tr>
            <th class="text-center">
                <label for="bill_total">Total</label>
            </th>
            <th class="text-center">{{ datas.price }} €</th>
        </tr>
    </table>

</body>